name: Testing
on: [push, pull_request]
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Latest Version
            os: ubuntu-latest
            python-version: '3.12'
            toxenv: py312-test
          
          - name: Oldest Version
            os: ubuntu-latest
            python-version: '3.8'
            toxenv: py38-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda w/ Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install Dependencies
        shell: bash -el {0}
        run: |
          pip install tox-conda
      - name: Run Tests
        shell: bash -el {0}
        run: |
          tox -e ${{ matrix.toxenv }} ${{ matrix.toxargs }} -- ${{ matrix.toxposargs }}
